services:
  scanner:
    build: .
    container_name: cve-2023-36845
    environment:
      - COOKIE_URL=${COOKIE_URL}
      - TARGETS_URL=${TARGETS_URL}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      - ./output:/app/output
    restart: unless-stopped
