database_url: postgresql://subenum:subenum@subenum-db:5432/subenum

chaos_api_key: API_KEY

timeouts:
    default: 900
    shuffledns: 3600
    portscan: 3600
    screenshots: 7200

paths:
    resolvers: /wordlists/resolvers.txt
    subdomains_wordlist: /wordlists/internal-subdomains.txt

tool_config_paths:
    subfinder: ""

scheduler:
    enabled: false
    times:
        - "00:00"
        - "06:00"
        - "12:00"
        - "18:00"
    targets:
        - example.com

notifications:
    discord:
        enabled: false
        webhook_url: https://discord.com/
        notify_on_new: true
        notify_on_reappeared: false
        max_domains_shown: 10
